- name: Download ${{ inputs.artifact-name }} file from artifacts
  uses: actions/download-artifact@v4
  with:
    name: ${{ inputs.artifact-name }}

- name: Log into Azure
  uses: azure/login@v2
  with:
    client-id: ${{ inputs.clientId }}
    tenant-id: ${{ inputs.tenantId }}
    subscription-id: ${{ inputs.subscriptionId }}

- name: Deploy Functions
  uses: azure/functions-action@v1
  with:
    app-name: ${{ inputs.app-name }}
    sku: flexconsumption
    remote-build: true
          
