name: Build and deploy Node.js project to Azure Function App - reproquintus

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'  # This will point to the extracted artifact
  NODE_VERSION: '22'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Upload deployment files
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: .

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: .

      - name: List contents for verification
        run: ls -R .

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_ABA9585D453749A78341937BCEFB7955 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_065BD260CCC449E3A5AEADA393E3FBA5 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_986EC33713FC4ABF96BCE74850B3B233 }}

      - name: Deploy to Azure Functions
        uses: Azure/functions-action@v1
        with:
          app-name: 'reproquintus'
          sku: flexconsumption
          remote-build: true
